export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_ERROR = 'USER_DATA_ERROR';

export const TODO_DATA_REQUEST = 'TODO_DATA_REQUEST';
export const TODO_DATA_SUCCESS = 'TODO_DATA_SUCCESS';
export const TODO_DATA_ERROR = 'TODO_DATA_ERROR';
